/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as BonusRouteImport } from './routes/bonus'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ModuloSlugRouteImport } from './routes/modulo.$slug'
import { Route as BonusSlugRouteImport } from './routes/bonus_.$slug'
import { Route as ModuloSlugBlocoBlockIdRouteImport } from './routes/modulo_.$slug.bloco.$blockId'
import { Route as ModuloSlugAulaLessonIdRouteImport } from './routes/modulo_.$slug.aula.$lessonId'

const BonusRoute = BonusRouteImport.update({
  id: '/bonus',
  path: '/bonus',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ModuloSlugRoute = ModuloSlugRouteImport.update({
  id: '/modulo/$slug',
  path: '/modulo/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BonusSlugRoute = BonusSlugRouteImport.update({
  id: '/bonus_/$slug',
  path: '/bonus/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ModuloSlugBlocoBlockIdRoute = ModuloSlugBlocoBlockIdRouteImport.update({
  id: '/modulo_/$slug/bloco/$blockId',
  path: '/modulo/$slug/bloco/$blockId',
  getParentRoute: () => rootRouteImport,
} as any)
const ModuloSlugAulaLessonIdRoute = ModuloSlugAulaLessonIdRouteImport.update({
  id: '/modulo_/$slug/aula/$lessonId',
  path: '/modulo/$slug/aula/$lessonId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bonus': typeof BonusRoute
  '/bonus/$slug': typeof BonusSlugRoute
  '/modulo/$slug': typeof ModuloSlugRoute
  '/modulo/$slug/aula/$lessonId': typeof ModuloSlugAulaLessonIdRoute
  '/modulo/$slug/bloco/$blockId': typeof ModuloSlugBlocoBlockIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bonus': typeof BonusRoute
  '/bonus/$slug': typeof BonusSlugRoute
  '/modulo/$slug': typeof ModuloSlugRoute
  '/modulo/$slug/aula/$lessonId': typeof ModuloSlugAulaLessonIdRoute
  '/modulo/$slug/bloco/$blockId': typeof ModuloSlugBlocoBlockIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bonus': typeof BonusRoute
  '/bonus_/$slug': typeof BonusSlugRoute
  '/modulo/$slug': typeof ModuloSlugRoute
  '/modulo_/$slug/aula/$lessonId': typeof ModuloSlugAulaLessonIdRoute
  '/modulo_/$slug/bloco/$blockId': typeof ModuloSlugBlocoBlockIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/bonus'
    | '/bonus/$slug'
    | '/modulo/$slug'
    | '/modulo/$slug/aula/$lessonId'
    | '/modulo/$slug/bloco/$blockId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/bonus'
    | '/bonus/$slug'
    | '/modulo/$slug'
    | '/modulo/$slug/aula/$lessonId'
    | '/modulo/$slug/bloco/$blockId'
  id:
    | '__root__'
    | '/'
    | '/bonus'
    | '/bonus_/$slug'
    | '/modulo/$slug'
    | '/modulo_/$slug/aula/$lessonId'
    | '/modulo_/$slug/bloco/$blockId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BonusRoute: typeof BonusRoute
  BonusSlugRoute: typeof BonusSlugRoute
  ModuloSlugRoute: typeof ModuloSlugRoute
  ModuloSlugAulaLessonIdRoute: typeof ModuloSlugAulaLessonIdRoute
  ModuloSlugBlocoBlockIdRoute: typeof ModuloSlugBlocoBlockIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/bonus': {
      id: '/bonus'
      path: '/bonus'
      fullPath: '/bonus'
      preLoaderRoute: typeof BonusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/modulo/$slug': {
      id: '/modulo/$slug'
      path: '/modulo/$slug'
      fullPath: '/modulo/$slug'
      preLoaderRoute: typeof ModuloSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bonus_/$slug': {
      id: '/bonus_/$slug'
      path: '/bonus/$slug'
      fullPath: '/bonus/$slug'
      preLoaderRoute: typeof BonusSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/modulo_/$slug/bloco/$blockId': {
      id: '/modulo_/$slug/bloco/$blockId'
      path: '/modulo/$slug/bloco/$blockId'
      fullPath: '/modulo/$slug/bloco/$blockId'
      preLoaderRoute: typeof ModuloSlugBlocoBlockIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/modulo_/$slug/aula/$lessonId': {
      id: '/modulo_/$slug/aula/$lessonId'
      path: '/modulo/$slug/aula/$lessonId'
      fullPath: '/modulo/$slug/aula/$lessonId'
      preLoaderRoute: typeof ModuloSlugAulaLessonIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BonusRoute: BonusRoute,
  BonusSlugRoute: BonusSlugRoute,
  ModuloSlugRoute: ModuloSlugRoute,
  ModuloSlugAulaLessonIdRoute: ModuloSlugAulaLessonIdRoute,
  ModuloSlugBlocoBlockIdRoute: ModuloSlugBlocoBlockIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
